services:
  logger:
    build: .
    restart: always
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ./data:/app/raspberry/Temp
      - ./logs:/app/raspberry/Logs
    environment:
      - TZ=America/Santiago
    command: >
      --configuration ${CONFIG}
      --experiment-rep ${EXPERIMENT_REP}
      --pump-lot ${PUMP_LOT}
      --fluid ${FLUID}
      --hours-to-log ${HOURS:-48}
      --sampling-ms ${SAMPLING_MS:-1000}
      --raspberry-id ${RASPBERRY_PI_ID:-2}
